
- name: Run Zookeeper container
  docker_container:
    image: confluentinc/cp-zookeeper:latest
    state: started
    recreate: yes
    env:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - name: backend_network
        aliases:
          - zookeeper